In [1]:
import torch
print(torch.__version__)

2.4.0+cu124


## 1) Generate tensors with random numbers
- we can generate a tensor with specific number of random numbers in a specified range.
- we will use this while getting random batches from our training data (e.g. the romeo and juliet book)

In [7]:
randint = torch.randint(-100,100, (6,))
print(randint)

tensor([ 59, -83, -30, -33,  54,  26])


## 2) Creating tensors
- we use ``` torch.tensor() ``` to create a tensor where pass in values to create a tensor

In [9]:
tensor = torch.tensor([[19.10,25.06],[0.6,0.4],[1.8,2.0]])
print(tensor)

tensor([[19.1000, 25.0600],
        [ 0.6000,  0.4000],
        [ 1.8000,  2.0000]])


## 3) Creating a tensor filled with zeros
- creating a tensor with set dimensions filled with zeros
- we use ``` torch.zeros(x,y,z,...) ``` we can make a tensor filled with 0s of any valid dimension with it

In [14]:
zeros = torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 3) Creating a tensor filled with ones
- creating a tensor with set dimensions filled with ones
- we use ``` torch.ones(x,y,z,...) ``` we can make a tensor filled with 1s of any valid dimension with it

In [15]:
ones = torch.ones(2,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 3) Creating an empty tensor
- creating a tensor with set dimensions filled with very small or large numbers
- we use ``` torch.empty(x,y,z,...) ``` we can make a tensor filled with  very small or large number of any valid dimension with it