In [1]:
import torch
print(torch.__version__)
import time
import numpy as np

2.4.0+cu124


## 1) Generate tensors with random numbers
- we can generate a tensor with specific number of random numbers in a specified range.
- we will use this while getting random batches from our training data (e.g. the romeo and juliet book)

In [2]:
randint = torch.randint(-100,100, (6,))
print(randint)

tensor([  2,  62,  76,  28, -29,  22])


## 2) Creating tensors
- we use ``` torch.tensor() ``` to create a tensor where pass in values to create a tensor

In [3]:
tensor = torch.tensor([[19.10,25.06],[0.6,0.4],[1.8,2.0]])
print(tensor)

tensor([[19.1000, 25.0600],
        [ 0.6000,  0.4000],
        [ 1.8000,  2.0000]])


## 3) Creating a tensor filled with zeros
- creating a tensor with set dimensions filled with zeros
- we use ``` torch.zeros(x,y,z,...) ``` we can make a tensor filled with 0s of any valid dimension with it

In [4]:
zeros = torch.zeros(2,3)
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 3) Creating a tensor filled with ones
- creating a tensor with set dimensions filled with ones
- we use ``` torch.ones(x,y,z,...) ``` we can make a tensor filled with 1s of any valid dimension with it

In [5]:
ones = torch.ones(2,3)
print(ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 3) Creating an empty tensor
- creating a tensor with set dimensions filled with very small or large numbers
- we use ``` torch.empty(x,y,z,...) ``` we can make a tensor filled with  very small or large number of any valid dimension with it

In [6]:
empty = torch.empty(3,6)
print(empty)

emptyType = torch.empty((3,4), dtype=torch.int64)
print(emptyType)

tensor([[-1.6832e-16,  1.4616e-42,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


## 4) Creating a sorted tensor
- we use ``` torch.arange() ``` to create a tensor that is sorted, we can pass in a step value and start and end values so that it is sorted and has values which go from start to finish with the step value as difference between each value. If we just pass in a number it will have a step valye of 1 and end after that many numbers (the number is treated as the end value)

In [7]:
aranged = torch.arange(7)
print(aranged)

tensor([0, 1, 2, 3, 4, 5, 6])


## 5) Using linspace to create a tensor
- linspace takes in a start end and step value it goes from start to end in that many steps. in arrange the step is the differnce between each value, in linspace steps is the amount of total values that should be there.
- e.g in linspace if you have a step of 4 , there will be 4 values in total and difference is based on the start and end but in arrange the difference will be 4 if the step is 4
- a tensor is created with linspace using ``` torch.linspace() ```

In [8]:
linspace = torch.linspace(19,25, steps=5)
print(linspace)

tensor([19.0000, 20.5000, 22.0000, 23.5000, 25.0000])


## 10) Using logspace to create a tensor
- same as above but in log

In [9]:
logspace = torch.logspace( -15 , 15 , steps=5)
print(logspace)

tensor([1.0000e-15, 3.1623e-08, 1.0000e+00, 3.1623e+07, 1.0000e+15])


## 11) Creating a tensor with eye
- using ``` torch.eye() ``` we make a tensor with diagonal 1s , kinda looks like reduced row echelon form

In [23]:
eye = torch.eye(5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


## 12) Using empty like to make a tensor
- create an empty tensor like the one that is passed in (sane dimensions)

In [24]:
like = torch.empty_like(eye)
print(like)

tensor([[-1.6663e-16,  1.4616e-42,  0.0000e+00,  9.2196e-41,  2.3694e-38],
        [ 3.6013e-43,  2.3694e-38,  2.3694e-38,  2.3694e-38,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])


## 13) Multinomial distrubtion with tensors
- we will use this for predictions
    - [ 0 ,    1]
    - [0.3,  0.7]
    - 0.3 is index 0 , 0.7 is index 1
    - 0.3 * 100 = 30%
    - <u> \+ 0.7 * 100 = 70% </u>
    - 1 * 100 = 100%

In [28]:
probabilities = torch.tensor([0.3,0.7]) #30% , 70% , adds up to 100%
# 30% chance we get 0 (index), 70% change we get 1 (index)

distributed = torch.multinomial(probabilities, num_samples=10, replacement=True)

print(distributed)

tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 0])


## 14) Concatanating tensors
- we will use this while generating texts, we will concatnate what we predicted with what we are predicting nopw and so on
- e.g. [1,2,3,4] with [8,9,5,4] combined to make one tensor [1,2,3,4,8,9,5,4] which decoded back might be 'yungting' for example

In [13]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5,6,7,8])

combined = torch.cat((tensor1,tensor2),dim=0)

print(combined)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


## 15) Using tril (Triangle Lower)
- this blocks the future and gives one more context each time so that so that there is more knowledge/history as you go down so that we wont predict while seeing/ copying the answer
- tril means triangle lower as when you go lower more future context is there

In [14]:
tril = torch.tril(torch.ones(6,6))
anotherTensor = torch.tensor([[19.10,25.06,3,4,5,6],[0.6,0.4,3,4,5,6],[1.8,2.0,3,4,5,6],[19.10,25.06,3,4,5,6],[0.6,0.4,3,4,5,6],[1.8,2.0,3,4,5,6]])
tril2 = torch.tril(anotherTensor)
print(tril)
print(tril2)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[19.1000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.6000,  0.4000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.8000,  2.0000,  3.0000,  0.0000,  0.0000,  0.0000],
        [19.1000, 25.0600,  3.0000,  4.0000,  0.0000,  0.0000],
        [ 0.6000,  0.4000,  3.0000,  4.0000,  5.0000,  0.0000],
        [ 1.8000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000]])


## 16) Using triu (Triangle Upper)
- opposite of triangle lower shown above


In [15]:
triu = torch.triu(torch.ones(5,5))
print(triu)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


## 17) Masked fill & exponentiation
- very important
- to reach the stage above , all that needs to be done is exponentiate each element ,explained better with the example below :
- e.g.
    - the  ```torcj.exp()``` function uses a constant of 2.71
    - when 2.71 is exponentiated with 0 it results in 1
    - when it is exponentiated with 1 it results in 2.71
    - when it is exponentiated with '-inf'it results in 0

In [30]:
masked_fill = torch.zeros(6,6).masked_fill(torch.tril(torch.ones(6,6)) == 0, float('-inf'))
print('masked : ')
print(masked_fill)
print()
print('exponentiated : ')
torch.exp(masked_fill)

masked : 
tensor([[0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0.]])

exponentiated : 


tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

## 18) Transposing tensors
-

In [17]:
to_transpose = torch.zeros(3,4,5)
transposed = to_transpose.transpose(0,2)
transposed.shape

torch.Size([5, 4, 3])

## 19)

## 20)

# CPU vs GPU 

In [18]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


## 13) how long does our gpu take for creating a 1x1 tensor with zeros?

In [19]:
%%time
start_time = time.time()

zeros = torch.zeros(1,1)

end_time = time.time()

time_elapsed = end_time - start_time
print(f"{time_elapsed:.1000f}")

0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

- since the above example is quite simple and too small we cannot see how much time it takes ,we can copare a calculation that is done with numpy on cpu and the same with torch on gpu for a better comparison below : 

In [ ]:
%%time
#pls change this to 10k or lower based on your hardware i have a fully specced out pc with a 4090 so wanted to play around hahah
torch_rand1 = torch.rand(40000, 40000).to(device)
torch_rand2 = torch.rand(40000, 40000).to(device)
np_rand1 = torch.rand(40000,40000)
np_rand2 = torch.rand(40000,40000)

print("torch using gpu: ")

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()
time_elapsed = end_time - start_time
print(f"{time_elapsed:.10f}")


print("numpy using cpu: ")

start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
time_elapsed = end_time - start_time
print(f"{time_elapsed:.10f}")